import util
import platform

# GENERAL

IS_KEYBOARD_MODE = False
ADJUST_FOR_RETINA =  True if platform.system() == "Darwin" else False
IMAGES_FOLDER = 'pc_images'
CONFIDENCE = 0.95
REGION_WIDTH = 1000
REGION_HEIGHT = 1000

# SCRIPT BINDINGS

DEBUG = True                    # Displays extra logs to help with debugging keys
BENCHMARKING = True             # Displays benchmarking info
STOP_KEY = "."                  # Key to stop the python process
DEFAULT_KEYBOARD_KEY = '5'      # Default keyboard key you will press to engage the macros

# GAME KEY BINDINGS

# Action Bar 1
ACTION_BAR_1_BUTTON_1 = '1'
ACTION_BAR_1_BUTTON_2 = '2'
ACTION_BAR_1_BUTTON_3 = '3'
ACTION_BAR_1_BUTTON_4 = '4'
ACTION_BAR_1_BUTTON_5 = '5'
ACTION_BAR_1_BUTTON_6 = '6'
ACTION_BAR_1_BUTTON_7 = '7'
ACTION_BAR_1_BUTTON_8 = '8'
ACTION_BAR_1_BUTTON_9 = '9'
ACTION_BAR_1_BUTTON_10 = '0'
ACTION_BAR_1_BUTTON_11 = '-'
ACTION_BAR_1_BUTTON_12 = '='

# Action Bar 2
ACTION_BAR_2_BUTTON_1 = 'q'
ACTION_BAR_2_BUTTON_2 = 'e'
ACTION_BAR_2_BUTTON_3 = 'r'
ACTION_BAR_2_BUTTON_4 = 't'
ACTION_BAR_2_BUTTON_5 = 'y'
ACTION_BAR_2_BUTTON_6 = 'u'
ACTION_BAR_2_BUTTON_7 = 'i'
ACTION_BAR_2_BUTTON_8 = 'o'
ACTION_BAR_2_BUTTON_9 = 'p'
ACTION_BAR_2_BUTTON_10 = '['
ACTION_BAR_2_BUTTON_11 = ']'
ACTION_BAR_2_BUTTON_12 = '\\'

# Action Bar 4
ACTION_BAR_4_BUTTON_1 = '!'
ACTION_BAR_4_BUTTON_2 = '@'
ACTION_BAR_4_BUTTON_3 = '#'
ACTION_BAR_4_BUTTON_4 = '$'
ACTION_BAR_4_BUTTON_5 = '%'

# CONTROLLER KEYBINDS

# Base
GAMEPAD_LEFT = ACTION_BAR_1_BUTTON_1
GAMEPAD_UP = ACTION_BAR_1_BUTTON_2
GAMEPAD_RIGHT = ACTION_BAR_1_BUTTON_3
GAMEPAD_DOWN = ACTION_BAR_1_BUTTON_4
GAMEPAD_X = ACTION_BAR_1_BUTTON_5
GAMEPAD_Y = ACTION_BAR_1_BUTTON_6
GAMEPAD_B = ACTION_BAR_1_BUTTON_7
# GAMEPAD_A = ACTION_BAR_1_BUTTON_8 # Used by jump

# L Trigger Down
GAMEPAD_L_LEFT = ACTION_BAR_1_BUTTON_9
GAMEPAD_L_UP = ACTION_BAR_1_BUTTON_10
GAMEPAD_L_RIGHT = ACTION_BAR_1_BUTTON_11
GAMEPAD_L_DOWN = ACTION_BAR_1_BUTTON_12
GAMEPAD_L_X = ACTION_BAR_2_BUTTON_1
GAMEPAD_L_Y = ACTION_BAR_2_BUTTON_2
GAMEPAD_L_B = ACTION_BAR_2_BUTTON_3
GAMEPAD_L_A = ACTION_BAR_2_BUTTON_4

# R Trigger Down
GAMEPAD_R_LEFT = ACTION_BAR_2_BUTTON_5
GAMEPAD_R_UP = ACTION_BAR_2_BUTTON_6
GAMEPAD_R_RIGHT = ACTION_BAR_2_BUTTON_7
GAMEPAD_R_DOWN = ACTION_BAR_2_BUTTON_8
GAMEPAD_R_X = ACTION_BAR_2_BUTTON_9
GAMEPAD_R_Y = ACTION_BAR_2_BUTTON_10
GAMEPAD_R_B = ACTION_BAR_2_BUTTON_11
GAMEPAD_R_A = ACTION_BAR_2_BUTTON_12
