import util

# GENERAL

IS_KEYBOARD_MODE = False
REGION = util.getCornerRegion(1000, 1000)
IMAGES_FOLDER = 'pc_images'

# SCRIPT BINDINGS

DEBUG = True                    # Displays extra logs to help with debugging keys
STOP_KEY = "."                  # Key to stop the python process
DEFAULT_KEYBOARD_KEY = '5'      # Default keyboard key you will press to engage the macros

# GAME KEY BINDINGS

# Action Bar 1
ACTION_BAR_1_BUTTON_1 = '1'
ACTION_BAR_1_BUTTON_2 = '2'
ACTION_BAR_1_BUTTON_3 = '3'
ACTION_BAR_1_BUTTON_4 = '4'
ACTION_BAR_1_BUTTON_5 = '5'
ACTION_BAR_1_BUTTON_6 = '6'
ACTION_BAR_1_BUTTON_7 = '7'
ACTION_BAR_1_BUTTON_8 = '8'
ACTION_BAR_1_BUTTON_9 = '9'
ACTION_BAR_1_BUTTON_10 = '0'
ACTION_BAR_1_BUTTON_11 = '-'
ACTION_BAR_1_BUTTON_12 = '='

# Action Bar 2
ACTION_BAR_2_BUTTON_1 = 'Q'
ACTION_BAR_2_BUTTON_2 = 'E'
ACTION_BAR_2_BUTTON_3 = 'R'
ACTION_BAR_2_BUTTON_4 = 'T'
ACTION_BAR_2_BUTTON_5 = 'Y'
ACTION_BAR_2_BUTTON_6 = 'U'
ACTION_BAR_2_BUTTON_7 = 'I'
ACTION_BAR_2_BUTTON_8 = 'O'
ACTION_BAR_2_BUTTON_9 = 'P'
ACTION_BAR_2_BUTTON_10 = '['
ACTION_BAR_2_BUTTON_11 = ']'
ACTION_BAR_2_BUTTON_12 = '\\'

# CONTROLLER KEYBINDS

# Base
GAMEPAD_LEFT = ACTION_BAR_1_BUTTON_1
GAMEPAD_UP = ACTION_BAR_1_BUTTON_2
GAMEPAD_RIGHT = ACTION_BAR_1_BUTTON_3
GAMEPAD_DOWN = ACTION_BAR_1_BUTTON_4
GAMEPAD_X = ACTION_BAR_1_BUTTON_5
GAMEPAD_Y = ACTION_BAR_1_BUTTON_6
GAMEPAD_B = ACTION_BAR_1_BUTTON_7
# GAMEPAD_A = ACTION_BAR_1_BUTTON_8 # Used by jump

# L Trigger Down
GAMEPAD_L_LEFT = ACTION_BAR_1_BUTTON_9
GAMEPAD_L_UP = ACTION_BAR_1_BUTTON_10
GAMEPAD_L_RIGHT = ACTION_BAR_1_BUTTON_11
GAMEPAD_L_DOWN = ACTION_BAR_1_BUTTON_12
GAMEPAD_L_X = ACTION_BAR_2_BUTTON_1
GAMEPAD_L_Y = ACTION_BAR_2_BUTTON_2
GAMEPAD_L_B = ACTION_BAR_2_BUTTON_3
GAMEPAD_L_A = ACTION_BAR_2_BUTTON_4

# R Trigger Down
GAMEPAD_R_LEFT = ACTION_BAR_2_BUTTON_5
GAMEPAD_R_UP = ACTION_BAR_2_BUTTON_6
GAMEPAD_R_RIGHT = ACTION_BAR_2_BUTTON_7
GAMEPAD_R_DOWN = ACTION_BAR_2_BUTTON_8
GAMEPAD_R_X = ACTION_BAR_2_BUTTON_9
GAMEPAD_R_Y = ACTION_BAR_2_BUTTON_10
GAMEPAD_R_B = ACTION_BAR_2_BUTTON_11
GAMEPAD_R_A = ACTION_BAR_2_BUTTON_12
